### ISSUE TITLE
`IndexError: list index out of range` in `find_miseq_fastq_subdir()`

### ISSUE THREAD

**Issue by dfornika** [dfornika/symlink-illumina-fastq-by-project-id#25]
Ran into this error recently while attempting to create symlinks:

```
Traceback (most recent call last):
  File "symlink-seqs", line 648, in <module>
    main(args)
  File "symlink-seqs", line 622, in main
    fastq_paths = get_fastq_paths(config, run_dir, sample_ids, args.project_id)
  File "symlink-seqs", line 459, in get_fastq_paths
    fastq_subdir = find_miseq_fastq_subdir(run_dir)
  File "symlink-seqs", line 150, in find_miseq_fastq_subdir
    fastq_dir = fastq_dirs[-1]
IndexError: list index out of range
```

**Comment by dfornika** [comment]
This error was caused by a permissions issue. The latest run directory's group ownership was set incorrectly, meaning that the script couldn't read its contents.

We should log a warning and continue on to the next run instead of crashing in this case.
